# -*- coding: utf-8 -*-
"""Minería de Datos Corr 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dl7PRpgFRIkdcly_eLv4pbX9yW066wuW
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

datos = {
    'naranjas': [2, 3, 1, 0],
    'manzanas': [0, 3, 7, 1]
}

compras = pd.DataFrame(datos)

compras

url = 'https://raw.githubusercontent.com/ManarOmar/New-York-Airbnb-2019/master/AB_NYC_2019.csv'

data = pd.read_csv(url)
data = data.fillna(data.mean(numeric_only=True))

data.describe()

columnas = ['price', 'minimum_nights', 'number_of_reviews', 'reviews_per_month', 'calculated_host_listings_count', 'availability_365']
data[columnas].describe()

data.isnull().sum()

sin_reseñas = data['number_of_reviews'] == 0

print()

data.hist(bins=10, figsize=(10,6))
plt.tight_layout()
plt.show()

print('faltantes en reviews_per_moth:', data['reviews_per_month'])

data['neighbourhood'].value_counts()
data['room_type'].value_counts()
data['neighbourhood_group'].value_counts()

media = data['reviews_per_month'].mean()

print('media de reviews_per_month:', round(media, 2))

data['reviews_per_month'] = data['reviews_per_month'].fillna(0)
data['reviews_per_month'].isnull().sum()

numericas = data.select_dtypes(include=np.number)
numericas

data.boxplot(column= 'price', figsize=(8,10))
plt.ylabel('Precio por noche (USD)')

precio_minimo = 0
precio_maximo = 1000
datos_limpios = data[(data['price'] > precio_minimo) & (data['price'] <= precio_maximo)].copy()
print('Antes:', len(data), 'anuncios')

print('Después:', len(datos_limpios), 'anuncios')
datos_limpios['price'].describe()

datos_limpios.boxplot(column= 'price', figsize=(8,10))
plt.ylabel('Precio por noche (USD)')
plt.show()

datos_limpios['price'].hist(bins=50, figsize=(10,5))
plt.xlabel('precio por noche (USD)')
plt.ylabel('anuncios')
plt.title('Distribución de precios')
plt.show()

corte_economico = 80
corte_medio = 200

def categoria_precio(precio):
  if precio <= corte_economico:
    return 'Económico'
  elif precio <= corte_medio:
    return 'Medio'
  else:
    return 'Premium'

datos_limpios['categoria_precio'] = datos_limpios['price'].apply(categoria_precio)
datos_limpios['categoria_precio'].value_counts()

datos_limpios.groupby('neighbourhood_group')['price'].agg(['count', 'mean', 'median'])

datos_limpios.groupby(['neighbourhood_group', 'room_type'])['price'].median().unstack()

data.corr()

!pip install sweetviz

!pip install dtale

import seaborn as sns

# Seleccionar solo las columnas numéricas de datos_limpios
columnas_numericas = datos_limpios.select_dtypes(include=np.number).columns

# Calcular la matriz de correlación
correlacion = datos_limpios[columnas_numericas].corr()

# Visualizar la matriz de correlación con un mapa de calor
plt.figure(figsize=(12, 10))
sns.heatmap(correlacion, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Matriz de Correlación de Variables Numéricas')
plt.show()

import dtale
import dtale.app as dtale_app

dtale_app.USE_COLAB = True

d = dtale.show(data)

print(d)